"""
Post model - LinkedIn content generated
"""
from datetime import datetime, timezone
from sqlalchemy import String, Text, Integer, ForeignKey, DateTime, Enum
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum
from core.database import Base


class PostStatus(str, enum.Enum):
    PENDING = "pending"
    GENERATING = "generating"
    READY = "ready"
    PUBLISHED = "published"
    FAILED = "failed"


class PostType(str, enum.Enum):
    AUTO = "auto"       # Generated by scheduler
    MANUAL = "manual"   # Generated from user URL


class Post(Base):
    __tablename__ = "posts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False)

    # Type and status
    post_type: Mapped[PostType] = mapped_column(Enum(PostType), default=PostType.AUTO)
    status: Mapped[PostStatus] = mapped_column(Enum(PostStatus), default=PostStatus.PENDING)

    # Source data
    source_url: Mapped[str] = mapped_column(String(2048), nullable=True)
    economic_news_title: Mapped[str] = mapped_column(String(500), nullable=True)
    economic_news_content: Mapped[str] = mapped_column(Text, nullable=True)
    economic_news_url: Mapped[str] = mapped_column(String(2048), nullable=True)
    ai_news_title: Mapped[str] = mapped_column(String(500), nullable=True)
    ai_news_content: Mapped[str] = mapped_column(Text, nullable=True)
    ephemeris: Mapped[str] = mapped_column(Text, nullable=True)

    # Generated content
    linkedin_post: Mapped[str] = mapped_column(Text, nullable=True)
    infographic_prompt: Mapped[str] = mapped_column(Text, nullable=True)

    # AI model used
    ai_provider: Mapped[str] = mapped_column(String(50), nullable=True)
    ai_model: Mapped[str] = mapped_column(String(100), nullable=True)

    # Error info
    error_message: Mapped[str] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    user = relationship("User", back_populates="posts")
